### PR TITLE
Up recycler view library. Fixed scroll listener issue

### PR DESCRIPTION
**Pull request by dehimb**
I have a complex views in my project and i faced some issues, when change view height dynamically.
I checked source code and fix my problems. I create a pull request, maybe it will be helpful for someone, who use latest recyclerview library

### CODE REVIEW

**Comment by blipinsk** [comment]
Hi, first of all thanks for the PR.
Now... we can't delete `@SuppressLint("NewApi")` from the `setupHeader` method because of the Api check within the `ViewTreeObserver` listener.
Apart from that I think that if we decide to use the newer version of the `RecyclerView`, we should also upgrade: `compileSdkVersion` to `22`, `buildToolsVersion` to `22.0.1`, `targetSdkVersion` to `22` (those three in both modules: `library` and `sample`), and `com.android.support:appcompat-v7` within the `sample` module to `22.2.1`.

**Comment by dehimb** [comment]
Ok. You can provide this changes without my pull request if need.

**Comment by blipinsk** [comment]
You can also just apply those changes to your PR :smirk: It's up to you

**Comment by dehimb** [comment]
Ok, i added necessary changes

**Pull request merged**
