### PR TITLE
Highlight java code snippets in Readme

### PR DESCRIPTION
**Pull request by vkotovv**
As proposed in #39

### CODE REVIEW

**Comment by vkotovv** [comment]
I think it still makes sense :)

**Comment by blipinsk** [comment]
I'd have to correct the indentation.
e.g. instead of this:

> 1. Create `RecyclerViewHeader` from `xml` using static initializer.
> 
> ``` java
>     RecyclerViewHeader header = RecyclerViewHeader.fromXml(context, R.layout.header);
> ```

use this:

> 1. Create `RecyclerViewHeader` from `xml` using static initializer.
>    
>    ``` java
>    RecyclerViewHeader header = RecyclerViewHeader.fromXml(context, R.layout.header);
>    ```

**Comment by vkotovv** [comment]
You're right, I've made changes and squashed my commits. It is ready for merge now.

**Comment by blipinsk** [comment]
Good, thanks :+1:

**Pull request merged**
